config_version = "0"

[plugins.downloads.taplo]
download_type = "gz"

[[plugins.downloads.taplo.system]]
cpu = "x86_64"
url = "https://github.com/tamasfe/taplo/releases/download/${version}/taplo-linux-x86_64.gz"

[[plugins.downloads.taplo.system]]
cpu = "aarch64"
url = "https://github.com/tamasfe/taplo/releases/download/${version}/taplo-linux-aarch64.gz"

[plugins.definitions.taplo]
downloads = ["taplo"]
file_types = ["toml"]
version_command = "taplo --version"
recommended = true
# direct_configs:
#         - .taplo.toml
#         - taplo.toml
#       environment:
#         - name: PATH
#           list: ["${linter}"]

# TODO: add support for taplo lint
# taplo has a hard to parse output format :(
#
# [plugins.definitions.taplo.drivers.lint]
# output = "stdout"
# output_format = "taplo"
# script = "/tmp/qlty/taplo lint ${target}"
# success_codes = [0, 1]
# batch = true
# cache_results = true

[plugins.definitions.taplo.drivers.format]
script = "taplo format ${target}"
success_codes = [0]
output = "rewrite"
batch = true
driver_type = "formatter"
cache_results = true
