config_version = "0"

[plugins.definitions.prettier]
runtime = "node"
package = "prettier"
file_types = [
  "typescript",
  "javascript",
  "css",
  "yaml",
  "html",
  "sass",
  "markdown",
  "json",
  "graphql",
]
# - prettier_supported_configs
version_command = "prettier --version"
recommended = true
# direct_configs:
#   - .prettierrc
#   - .prettierrc.json
#   - .prettierrc.yml
#   - .prettierrc.yaml
#   - .prettierrc.json5
#   - .prettierrc.js
#   - .prettierrc.cjs
#   - prettier.config.js
#   - prettier.config.cjs
#   - .prettierrc.toml
#   - .prettierignore
# affects_cache:
#   - package.json
#   - .editorconfig # Undocumented config file


[plugins.definitions.prettier.drivers.format]
script = "prettier -w ${target}"
success_codes = [0]
cache_results = true
output = "rewrite"
batch = true
driver_type = "formatter"
