config_version = 1

[plugins.definitions.rubocop]
runtime = "ruby"
package = "rubocop"
file_types = ["ruby", "gemspec"]
config_files = [".rubocop.yml"]
version_command = "rubocop --version"
recommended = true

[plugins.definitions.rubocop.drivers.lint]
script = "rubocop --format json ${target}"
success_codes = [0, 1, 2]
output = "stdout"
output_format = "rubocop"
cache_results = true
batch = true
max_batch = 100

[plugins.definitions.rubocop.drivers.format]
script = "rubocop --fix-layout ${target}"
success_codes = [0, 1, 2]
output = "rewrite"
batch = true
driver_type = "formatter"
