config_version = "0"

[plugins.definitions.stylelint]
runtime = "node"
package = "stylelint"
file_types = ["css", "sass"]
config_files = [
  ".stylelintrc",
  ".stylelintrc.cjs",
  ".stylelintrc.js",
  ".stylelintrc.json",
  ".stylelintrc.yaml",
  ".stylelintrc.yml",
]
version_command = "stylelint --version"

[plugins.definitions.stylelint.drivers.lint]
script = "stylelint --formatter json ${target}"
success_codes = [0, 2]
error_codes = [1, 78]
output = "stdout"
output_format = "stylelint"
cache_results = true
batch = true
max_batch = 100

[plugins.definitions.stylelint.drivers.format]
script = "stylelint --fix ${target}"
success_codes = [0, 2]
error_codes = [1, 78]
cache_results = true
output = "rewrite"
batch = true
driver_type = "formatter"
